# Generated by Django 3.0.4 on 2020-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='images/')),
                ('small_text', models.CharField(max_length=50)),
                ('large_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('alt_text', models.CharField(max_length=50)),
                ('display_on_index', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=100)),
                ('insta', models.URLField(default='')),
                ('linkdin', models.URLField(default='')),
                ('member_img', models.ImageField(upload_to='images/members')),
                ('sig_head', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/sponsors')),
            ],
        ),
    ]
