# Generated by Django 3.0.4 on 2020-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200429_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roll_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
