# Generated by Django 3.0.4 on 2020-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200429_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_filter',
            field=models.IntegerField(default=0),
        ),
    ]
