# Generated by Django 3.0.4 on 2020-05-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
