# Generated by Django 3.0.4 on 2020-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitstop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('edition', models.DateField()),
            ],
        ),
    ]
