# Generated by Django 3.0.4 on 2020-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_pitstop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitstop',
            name='url',
        ),
        migrations.AddField(
            model_name='pitstop',
            name='Google_id',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='pitstop',
            name='edition',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
