# Generated by Django 3.0.5 on 2020-05-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200513_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_link',
            field=models.URLField(default=' '),
        ),
    ]
