# Generated by Django 3.0.4 on 2020-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_sponsor_sponsor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='writeup',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
