# Generated by Django 3.0.4 on 2020-05-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstop',
            name='cover',
            field=models.ImageField(blank=True, upload_to='pits'),
        ),
    ]
