# Generated by Django 3.0.4 on 2020-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_pitstop_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
