# Generated by Django 3.0.4 on 2020-05-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200517_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstop',
            name='link',
            field=models.URLField(default='../#'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='small_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pitstop',
            name='Google_id',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
