# Generated by Django 3.0.4 on 2020-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20200517_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitstop',
            name='Google_id',
            field=models.CharField(blank=True, default=' ', help_text='ignor maadi!!! <br> leave blank', max_length=100),
        ),
    ]
