# Generated by Django 3.0.4 on 2020-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20200517_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='textNextToVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='this text will appear next to video')),
            ],
        ),
        migrations.AlterField(
            model_name='pitstop',
            name='Google_id',
            field=models.CharField(blank=True, default=' ', help_text='ignore maadi!!! <br> leave blank', max_length=100),
        ),
    ]
