# Generated by Django 3.0.4 on 2020-05-20 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20200520_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitstop',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
