# Generated by Django 3.0.4 on 2020-05-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_pitstop_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
