# Generated by Django 3.0.4 on 2020-05-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20200520_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
