# Generated by Django 3.0.4 on 2020-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20200520_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sig',
            field=models.IntegerField(choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (5, 'MEDIA'), (6, 'MARKETING')], default=0),
        ),
    ]
