# Generated by Django 3.0.4 on 2020-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20200520_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page_to_display',
            field=models.IntegerField(choices=[(1, 'home'), (2, 'about'), (3, 'team'), (4, 'contact'), (5, 'aero'), (6, 'VD'), (7, 'PWR'), (8, 'ELEC'), (9, 'gallery'), (10, 'media'), (11, 'market')], default=1),
        ),
    ]
