# Generated by Django 3.0.4 on 2020-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200520_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page_to_display',
            field=models.IntegerField(choices=[(1, 'home'), (2, 'about'), (3, 'team'), (4, 'contact'), (5, 'aero'), (6, 'VD'), (7, 'PWR'), (8, 'ELEC'), (11, 'gallery'), (10, 'media'), (9, 'market')], default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_filter',
            field=models.IntegerField(choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (6, 'MEDIA'), (5, 'MARKETING')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='sig',
            field=models.IntegerField(choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (6, 'MEDIA'), (5, 'MARKETING')], default=0),
        ),
    ]
