# Generated by Django 3.0.4 on 2020-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20200520_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitstop',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
