# Generated by Django 3.0.4 on 2020-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_auto_20200520_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('text_next_to_video', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='textNextToVideo',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.IntegerField(choices=[(0, 'cap'), (1, 'op'), (2, 'tech head'), (3, 'subsytem head'), (4, 'media/marketing'), (5, 'other')], default=5),
        ),
    ]
