# Generated by Django 3.0.4 on 2020-05-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_auto_20200529_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page_to_display',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'About'), (3, 'Team'), (4, 'Contact'), (5, 'Aero'), (6, 'VD'), (7, 'PWR'), (8, 'ELEC'), (11, 'Gallery'), (10, 'Media'), (9, 'Marketing')], default=1),
        ),
    ]
