# Generated by Django 3.0.5 on 2020-08-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_auto_20200529_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subsystem_filter',
            field=models.IntegerField(choices=[(5, 'INDEX'), (1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC')], default=0),
        ),
    ]
