# Generated by Django 3.0.5 on 2020-05-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('text_next_to_video', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_to_display', models.IntegerField(choices=[(1, 'Home'), (2, 'About'), (3, 'Team'), (4, 'Contact'), (5, 'Aero'), (6, 'VD'), (7, 'PWR'), (8, 'ELEC'), (11, 'Gallery'), (10, 'Media'), (9, 'Marketing')], default=1)),
                ('bg_img', models.ImageField(upload_to='images/ev/')),
                ('small_text', models.CharField(blank=True, max_length=50)),
                ('large_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='3dModels/ev/')),
                ('subsystem_filter', models.IntegerField(choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC')], default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/ev/')),
                ('alt_text', models.CharField(blank=True, max_length=50)),
                ('display_on_index', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('roll_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(0, 'cap'), (1, 'op'), (2, 'tech head'), (3, 'subsytem head'), (4, 'media/marketing'), (5, 'other')], default=5)),
                ('sig', models.IntegerField(choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (6, 'MEDIA'), (5, 'MARKETING')], default=0)),
                ('writeup', models.CharField(blank=True, max_length=144)),
                ('member_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=300)),
                ('insta', models.URLField(default='')),
                ('linkdin', models.URLField(default='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('member_img', models.ImageField(upload_to='images/ev/members')),
                ('sig_head', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Pitstop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='#')),
                ('edition', models.CharField(default=' ', max_length=100)),
                ('created_on', models.DateTimeField()),
                ('cover', models.ImageField(blank=True, upload_to='pits')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/ev/sponsors')),
                ('sponsor_link', models.URLField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('blog_filter', models.IntegerField(choices=[(1, 'AERO'), (2, 'VD'), (3, 'PWR'), (4, 'ELEC'), (6, 'MEDIA'), (5, 'MARKETING')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='nitkracing_ev.Member')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
