# Generated by Django 3.0.5 on 2020-06-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkracing_ev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_us_content',
            new_name='AboutUsContent',
        ),
        migrations.AlterField(
            model_name='banner',
            name='page_to_display',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'About'), (3, 'Team'), (4, 'Contact'), (5, 'EPOWERTRAIN'), (6, 'VD'), (7, 'BATTERY'), (8, 'LV'), (9, 'CHASSIS'), (12, 'Gallery'), (11, 'Media'), (10, 'Marketing')], default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_filter',
            field=models.IntegerField(choices=[(1, 'EPOWERTRAIN'), (2, 'VD'), (3, 'BATTERY'), (4, 'LV'), (5, 'CHASSIS'), (6, 'MEDIA'), (7, 'MARKETING')], default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='subsystem_filter',
            field=models.IntegerField(choices=[(1, 'EPOWERTRAIN'), (2, 'VD'), (3, 'BATTERY'), (4, 'LV'), (5, 'CHASSIS')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='sig',
            field=models.IntegerField(choices=[(1, 'EPOWERTRAIN'), (2, 'VD'), (3, 'BATTERY'), (4, 'LV'), (5, 'CHASSIS'), (6, 'MEDIA'), (7, 'MARKETING')], default=0),
        ),
    ]
