# Generated by Django 3.0.5 on 2020-08-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitkracing_ev', '0002_auto_20200623_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subsystem_filter',
            field=models.IntegerField(choices=[(6, 'INDEX'), (1, 'EPOWERTRAIN'), (2, 'VD'), (3, 'BATTERY'), (4, 'LV'), (5, 'CHASSIS')], default=0),
        ),
    ]
